version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

#  sonarqube:
#    image: sonarqube:6.4
#    ports:
#      - 9000:9000
#    environment:
#      - TZ=Europe/Amsterdam
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#    volumes:
#      - ./sonarqube_conf:/opt/sonarqube/conf
#      - ./sonarqube_data:/opt/sonarqube/data
